name: main

on: push


env:
  # IMAGE: python
  AUTHENTICATION_SERVER: 0.0.0.0
  FULL_IMAGE: python

jobs:
  notify-ducc:
    runs-on: self-hosted
    permissions:
      id-token: write  # This is required for OIDC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Get OIDC token
        id: get_token
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: notify ducc
        run: |
          curl -X "POST" \
              -H "Authorization:${{ steps.get_token.outputs.token }}" \
              "${{ env.AUTHENTICATION_SERVER }}:8000/api/github/sync/jwt?image=${{ env.FULL_IMAGE }}"
